language: ruby
rvm:
  - 2.2.0
before_script:
  - psql -c 'create database leket_app_test;' -U postgres
script:
 - RAILS_ENV=test bin/rake db:migrate
 - bundle exec rake db:test:prepare
 - bundle exec rspec spec
